"""The `build` and `profile` tools: two-phase Halide build + benchmarking.

Per the decided build-driver split (idea.md Build Tool): ninja builds the
param-independent steps once (the C++ workspace -> generator executable, and
RunGenMain.o); Python drives the param-dependent steps serially with
subprocess (generator emit -> link -> optional benchmark run).

Failure handling follows idea.md Tool Safety Requirements: bad build *outcomes*
(`c++ error` / `halide error`) and the generator-count harness error are NOT
rollback-triggering exceptions; the node is still flushed/committed, and only
the process exit code reflects the failure.
"""

import json
import os
import socket
import subprocess
import sys

from . import ids
from . import safety
from .context import Context
from .errors import DhHlError, HarnessError
from . import ninja_syntax

# ---- Halide location (magic constants; see idea.md FUTURE notes) -----------
HALIDE_BUILD = os.path.expanduser("~/Halide/build")
HALIDE_ROOT = os.path.expanduser("~/Halide")

_INC_BUILD = os.path.join(HALIDE_BUILD, "include")
_SRC_RUNTIME = os.path.join(HALIDE_ROOT, "src", "runtime")
_SOURCE_TOOLS = os.path.join(HALIDE_ROOT, "tools")
_GENGEN_A = os.path.join(HALIDE_BUILD, "tools", "libHalide_GenGen.a")
_HALIDE_LIBDIR = os.path.join(HALIDE_BUILD, "src")
_RUNGENMAIN_CPP = os.path.join(_SOURCE_TOOLS, "RunGenMain.cpp")

_GEN_EXE = "dh_hl_generator"
_OUT_BASENAME = "dh_hl_gen"        # fixed, so emitted filenames are stable
_RUNGEN_BIN = _OUT_BASENAME + ".rungen"

_RESULT_RANK = {"c++ error": 0, "halide error": 1, "success": 2}

_CXX = "c++"


# ---------------------------------------------------------------------------
# subprocess helpers
# ---------------------------------------------------------------------------

def _run_streamed(cmd, cwd=None, env=None):
    """Run *cmd*, letting its stdout/stderr flow to ours.  Returns exit code."""
    print("+ " + " ".join(cmd), file=sys.stderr)
    return subprocess.run(cmd, cwd=cwd, env=env).returncode


def _run_capture(cmd, cwd=None):
    """Run *cmd*, capturing combined output.  Returns (rc, text)."""
    p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                       stderr=subprocess.STDOUT, universal_newlines=True)
    return p.returncode, p.stdout


# ---------------------------------------------------------------------------
# generator parameter formatting
# ---------------------------------------------------------------------------

def _format_param_value(v):
    """Format a generator parameter value as a key=value token payload.

    Whole numbers with %d, non-whole with a full-precision repr (no roundoff);
    see the NB in the Build Tool section of idea.md."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return "%d" % v
    if isinstance(v, float):
        if v.is_integer():
            return "%d" % int(v)
        return repr(v)
    if isinstance(v, str):
        return v
    raise DhHlError("unsupported generator parameter value: " + repr(v))


def _param_tokens(params):
    return ["{}={}".format(k, _format_param_value(v)) for k, v in params.items()]


def _load_params_object(path):
    """A generator-parameters file for `build`: a single JSON object."""
    if path is None:
        return {}
    with open(path, "r", encoding="utf-8") as f:
        obj = json.load(f)
    if not isinstance(obj, dict):
        raise DhHlError("parameters file must hold a JSON object")
    return obj


def _load_params_list(path):
    """A generator-parameters file for `profile`: [{}] default, [obj] for a
    single object, or the list verbatim."""
    if path is None:
        return [{}]
    with open(path, "r", encoding="utf-8") as f:
        obj = json.load(f)
    if isinstance(obj, dict):
        return [obj]
    if isinstance(obj, list):
        return obj
    raise DhHlError("parameters file must hold a JSON object or list")


# ---------------------------------------------------------------------------
# ninja: phase 1 (generator exe) + RunGenMain.o
# ---------------------------------------------------------------------------

def _write_ninja(bin_dir, workspace_path):
    """Write bin/build_ninja.txt building the two param-independent artifacts.
    Returns its path."""
    path = os.path.join(bin_dir, "build_ninja.txt")
    if os.path.exists(path):
        os.remove(path)  # regenerate; it lives in the gitignored bin/
    with open(path, "w", encoding="utf-8") as f:
        n = ninja_syntax.Writer(f)
        n.comment("Auto-generated by dh_hl; param-independent build steps only.")
        gen_flags = "-std=c++17 -O2 -I{} -I{}".format(_INC_BUILD, _SOURCE_TOOLS)
        gen_ld = "{} -L{} -lHalide -Wl,-rpath,{}".format(
            _GENGEN_A, _HALIDE_LIBDIR, _HALIDE_LIBDIR)
        rungen_flags = ("-std=c++17 -O2 -fno-exceptions -DHALIDE_NO_PNG "
                        "-DHALIDE_NO_JPEG -I{} -I{} -I{} -I.".format(
                            _INC_BUILD, _SRC_RUNTIME, _SOURCE_TOOLS))
        n.variable("cxx", _CXX)
        n.newline()
        n.rule("gen_exe",
               command="$cxx {} $in -o $out {}".format(gen_flags, gen_ld),
               description="GEN-EXE $out")
        n.rule("rungenmain_obj",
               command="$cxx -c {} $in -o $out".format(rungen_flags),
               description="CXX RunGenMain.o")
        n.newline()
        n.build(_GEN_EXE, "gen_exe", os.path.abspath(workspace_path))
        n.build("RunGenMain.o", "rungenmain_obj", _RUNGENMAIN_CPP)
    return path


def _ninja_build(bin_dir, ninja_path, targets):
    cmd = ["ninja", "-f", os.path.basename(ninja_path)] + targets
    return _run_streamed(cmd, cwd=bin_dir)


def _discover_generator_name(bin_dir):
    """Run the generator exe with no -g and scrape the single registered name.
    Raises HarnessError if the count isn't exactly one."""
    rc, out = _run_capture(["./" + _GEN_EXE], cwd=bin_dir)
    names = []
    lines = out.splitlines()
    for i, line in enumerate(lines):
        if "available Generators are:" in line:
            for rest in lines[i + 1:]:
                if rest.strip():
                    names.append(rest.strip())
                else:
                    break
            break
    if len(names) != 1:
        raise HarnessError(
            "expected exactly one registered generator (single-generator "
            "assumption), found {}: {}".format(len(names), names))
    return names[0]


# ---------------------------------------------------------------------------
# phase 2 (emit) + phase 4 (link) + run
# ---------------------------------------------------------------------------

def _emit(bin_dir, gen_name, params, with_stmt):
    emits = ["static_library", "c_header", "registration"]
    if with_stmt:
        emits.append("conceptual_stmt")
    cmd = (["./" + _GEN_EXE, "-g", gen_name, "-o", ".", "-f", _OUT_BASENAME]
           + _param_tokens(params)
           + ["-e", ",".join(emits), "target=host-profile"])
    return _run_streamed(cmd, cwd=bin_dir)


def _link(bin_dir):
    cmd = [_CXX, "-std=c++17", "-O2", "RunGenMain.o",
           _OUT_BASENAME + ".registration.cpp", _OUT_BASENAME + ".a",
           "-o", _RUNGEN_BIN, "-lpthread", "-ldl"]
    return _run_streamed(cmd, cwd=bin_dir)


def _run_benchmark(bin_dir, json_out_path):
    env = dict(os.environ)
    env["HL_PROFILER_JSON_OUTPUT"] = json_out_path
    cmd = ["./" + _RUNGEN_BIN, "--verbose", "--benchmarks=all", "--estimate_all"]
    return _run_streamed(cmd, cwd=bin_dir, env=env)


def _upgrade_result(node, new_result):
    if _RESULT_RANK[new_result] > _RESULT_RANK[node.result]:
        node.set_result(new_result)


# ---------------------------------------------------------------------------
# node selection (step 1, shared by build & profile)
# ---------------------------------------------------------------------------

def _select_node(ctx):
    unamb = ctx.unambiguous_schedule()
    if unamb is not None:
        return unamb
    catalog = ctx.catalog
    cis = catalog.current_idea_state
    if cis.kind == "idea":
        idea = catalog.get_idea(cis.idea_id)
        return catalog.create_schedule(ctx.workspace_source, parent_idea=idea)
    raise DhHlError(
        "no unambiguous schedule node and no current idea node; use "
        "`dh_hl set_idea <idea>` to pick an idea, or `dh_hl new_root` to "
        "start a new root")


# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------

def cmd_build(args):
    ctx = Context(args.workspace)
    ctx.require_workspace()
    ctx.ensure_catalog_rw()
    bin_dir = ctx.catalog.bin_dir
    params = _load_params_object(args.parameters)

    node = _select_node(ctx)  # pre-flight; may raise (rollback safe: nothing built)

    # Past this point the node exists and must persist even on harness error;
    # so harness errors flush-then-exit rather than propagating to rollback.
    try:
        ninja_path = _write_ninja(bin_dir, ctx.workspace_path)

        # Phase 1: C++ -> generator exe.  Failure => c++ error outcome.
        if _ninja_build(bin_dir, ninja_path, [_GEN_EXE]) != 0:
            _upgrade_result(node, "c++ error")
            _finish_and_exit(ctx, node, ok=False, stmt_path=None)

        # Generator-count harness check (after C++ compiled): no result update.
        gen_name = _discover_generator_name(bin_dir)

        # RunGenMain.o is harness infra; its failure is a harness error.
        if _ninja_build(bin_dir, ninja_path, ["RunGenMain.o"]) != 0:
            raise HarnessError("failed to compile RunGenMain.o")

        # Phase 2: emit (with conceptual_stmt for build).
        if _emit(bin_dir, gen_name, params, with_stmt=True) != 0:
            _upgrade_result(node, "halide error")
            _finish_and_exit(ctx, node, ok=False, stmt_path=None)
        _upgrade_result(node, "success")

        # Phase 4: link a standalone benchmarkable binary.
        if _link(bin_dir) != 0:
            raise HarnessError("failed to link the standalone RunGen binary")

        stmt_path = os.path.join(bin_dir, _OUT_BASENAME + ".conceptual.stmt")
        _finish_and_exit(ctx, node, ok=True, stmt_path=stmt_path)
    except HarnessError as e:
        print("dh_hl: " + str(e), file=sys.stderr)
        _finish_and_exit(ctx, node, ok=False, stmt_path=None)


# ---------------------------------------------------------------------------
# profile
# ---------------------------------------------------------------------------

def cmd_profile(args):
    ctx = Context(args.workspace)
    ctx.require_workspace()
    ctx.ensure_catalog_rw()
    bin_dir = ctx.catalog.bin_dir
    param_list = _load_params_list(args.parameters)

    node = _select_node(ctx)

    try:
        ninja_path = _write_ninja(bin_dir, ctx.workspace_path)

        if _ninja_build(bin_dir, ninja_path, [_GEN_EXE]) != 0:
            _upgrade_result(node, "c++ error")
            _finish_and_exit(ctx, node, ok=False, stmt_path=None)

        gen_name = _discover_generator_name(bin_dir)

        if _ninja_build(bin_dir, ninja_path, ["RunGenMain.o"]) != 0:
            raise HarnessError("failed to compile RunGenMain.o")

        hostname = socket.gethostname()
        all_ok = True
        for params in param_list:
            # Phase 2: emit (no stmt needed for profiling).
            if _emit(bin_dir, gen_name, params, with_stmt=False) != 0:
                _upgrade_result(node, "halide error")
                all_ok = False
                continue  # skip this parameter set, keep going
            _upgrade_result(node, "success")

            if _link(bin_dir) != 0:
                all_ok = False
                continue

            # Benchmark run monopolizes the machine (serial; no parallelism).
            bench_ts = ctx.catalog.fresh_timestamp()  # busy-waits past dups
            # MUST be absolute: it is handed to the benchmark child via
            # HL_PROFILER_JSON_OUTPUT, and the child runs with cwd=bin_dir, so a
            # bin_dir-relative path would be resolved against bin_dir twice.
            json_out = os.path.abspath(os.path.join(bin_dir, "profile_out.json"))
            if os.path.exists(json_out):
                os.remove(json_out)
            if _run_benchmark(bin_dir, json_out) != 0:
                all_ok = False
                continue

            try:
                bench_obj = _build_benchmark_obj(json_out, hostname, params)
            except HarnessError as e:
                print("dh_hl: skipping parameter set: " + str(e),
                      file=sys.stderr)
                all_ok = False
                continue
            node.add_benchmark(hostname, bench_ts, bench_obj)

        _finish_and_exit(ctx, node, ok=all_ok, stmt_path=None)
    except HarnessError as e:
        print("dh_hl: " + str(e), file=sys.stderr)
        _finish_and_exit(ctx, node, ok=False, stmt_path=None)


def _build_benchmark_obj(json_out, hostname, params):
    with open(json_out, "r", encoding="utf-8") as f:
        prof = json.load(f)
    pipelines = prof.get("pipelines")
    if not isinstance(pipelines, list) or len(pipelines) != 1:
        raise HarnessError(
            "profiler JSON must have exactly one pipeline (got {})".format(
                None if not isinstance(pipelines, list) else len(pipelines)))
    try:
        cpu_count = os.cpu_count() or 0
    except NotImplementedError:
        cpu_count = 0
    return {
        "hostname": hostname,
        "cpu_count": cpu_count,
        "parameters": params,
        "profiler": pipelines[0],
    }


# ---------------------------------------------------------------------------
# shared finish
# ---------------------------------------------------------------------------

def _finish_and_exit(ctx, node, ok, stmt_path):
    """Flush the (possibly failed-outcome) node exactly once, print the stmt
    path and node ID, then exit with a status reflecting *ok*."""
    if stmt_path is not None:
        print(stmt_path)
    ctx.finish()
    # Node ID is the last thing printed (after all subprocess output).
    print(ctx.catalog.format_schedule_id(node))
    sys.exit(0 if ok else 1)
